<?php
/**
 * BrandReview
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PicThrive Internal API
 *
 * Detailed docs about our API, including hidden fields not publicly displayed.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * BrandReview Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BrandReview implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Brand_Review';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'trip_advisor_url' => 'string',
        'google_cid' => 'string',
        'yelp_url' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'trip_advisor_url' => null,
        'google_cid' => null,
        'yelp_url' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'trip_advisor_url' => 'TripAdvisorUrl',
        'google_cid' => 'GoogleCid',
        'yelp_url' => 'YelpUrl'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'trip_advisor_url' => 'setTripAdvisorUrl',
        'google_cid' => 'setGoogleCid',
        'yelp_url' => 'setYelpUrl'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'trip_advisor_url' => 'getTripAdvisorUrl',
        'google_cid' => 'getGoogleCid',
        'yelp_url' => 'getYelpUrl'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['trip_advisor_url'] = isset($data['trip_advisor_url']) ? $data['trip_advisor_url'] : null;
        $this->container['google_cid'] = isset($data['google_cid']) ? $data['google_cid'] : null;
        $this->container['yelp_url'] = isset($data['yelp_url']) ? $data['yelp_url'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets trip_advisor_url
     *
     * @return string|null
     */
    public function getTripAdvisorUrl()
    {
        return $this->container['trip_advisor_url'];
    }

    /**
     * Sets trip_advisor_url
     *
     * @param string|null $trip_advisor_url A url to your Company TripAdvisor Page
     *
     * @return $this
     */
    public function setTripAdvisorUrl($trip_advisor_url)
    {
        $this->container['trip_advisor_url'] = $trip_advisor_url;

        return $this;
    }

    /**
     * Gets google_cid
     *
     * @return string|null
     */
    public function getGoogleCid()
    {
        return $this->container['google_cid'];
    }

    /**
     * Sets google_cid
     *
     * @param string|null $google_cid A unique Customer id for your Companies Google page. Plan to deprecate this.
     *
     * @return $this
     */
    public function setGoogleCid($google_cid)
    {
        $this->container['google_cid'] = $google_cid;

        return $this;
    }

    /**
     * Gets yelp_url
     *
     * @return string|null
     */
    public function getYelpUrl()
    {
        return $this->container['yelp_url'];
    }

    /**
     * Sets yelp_url
     *
     * @param string|null $yelp_url A url to your Company Yelp Page
     *
     * @return $this
     */
    public function setYelpUrl($yelp_url)
    {
        $this->container['yelp_url'] = $yelp_url;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}


