<?php
/**
 * Video
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PicThrive Internal API
 *
 * Detailed docs about our API, including hidden fields not publicly displayed.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * Video Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Video implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Video';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'owner_id' => 'string',
        'group_id' => 'string',
        'video_id' => 'string',
        'created' => 'int',
        'sort_order' => 'string',
        'width' => 'int',
        'height' => 'int',
        'duration' => 'string',
        'original' => 'string',
        'state' => 'string',
        'deleted' => 'bool',
        'resolution_name' => 'string',
        'static_small' => 'string',
        'static_medium' => 'string',
        'static_watermark_small' => 'string',
        'static_watermark_medium' => 'string',
        'small_preview' => 'string',
        'small_preview_gif' => 'string',
        'watermark_small' => 'string',
        'watermark_small_gif' => 'string',
        'medium_preview' => 'string',
        'medium_preview_gif' => 'string',
        'watermark_medium' => 'string',
        'watermark_medium_gif' => 'string',
        'stream480p' => 'string',
        'source_video_id' => 'string',
        'is360' => 'bool',
        'stereo_mode' => 'string',
        'region' => '\OpenAPI\Client\Model\Region',
        'is_souvenir' => 'bool',
        'download_link' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'owner_id' => null,
        'group_id' => null,
        'video_id' => null,
        'created' => 'int32',
        'sort_order' => null,
        'width' => 'int32',
        'height' => 'int32',
        'duration' => null,
        'original' => null,
        'state' => null,
        'deleted' => null,
        'resolution_name' => null,
        'static_small' => null,
        'static_medium' => null,
        'static_watermark_small' => null,
        'static_watermark_medium' => null,
        'small_preview' => null,
        'small_preview_gif' => null,
        'watermark_small' => null,
        'watermark_small_gif' => null,
        'medium_preview' => null,
        'medium_preview_gif' => null,
        'watermark_medium' => null,
        'watermark_medium_gif' => null,
        'stream480p' => null,
        'source_video_id' => null,
        'is360' => null,
        'stereo_mode' => null,
        'region' => null,
        'is_souvenir' => null,
        'download_link' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'owner_id' => 'OwnerId',
        'group_id' => 'GroupId',
        'video_id' => 'VideoId',
        'created' => 'Created',
        'sort_order' => 'SortOrder',
        'width' => 'Width',
        'height' => 'Height',
        'duration' => 'Duration',
        'original' => 'Original',
        'state' => 'State',
        'deleted' => 'Deleted',
        'resolution_name' => 'ResolutionName',
        'static_small' => 'StaticSmall',
        'static_medium' => 'StaticMedium',
        'static_watermark_small' => 'StaticWatermarkSmall',
        'static_watermark_medium' => 'StaticWatermarkMedium',
        'small_preview' => 'SmallPreview',
        'small_preview_gif' => 'SmallPreviewGif',
        'watermark_small' => 'WatermarkSmall',
        'watermark_small_gif' => 'WatermarkSmallGif',
        'medium_preview' => 'MediumPreview',
        'medium_preview_gif' => 'MediumPreviewGif',
        'watermark_medium' => 'WatermarkMedium',
        'watermark_medium_gif' => 'WatermarkMediumGif',
        'stream480p' => 'Stream480p',
        'source_video_id' => 'SourceVideoId',
        'is360' => 'Is360',
        'stereo_mode' => 'StereoMode',
        'region' => 'Region',
        'is_souvenir' => 'IsSouvenir',
        'download_link' => 'DownloadLink'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'owner_id' => 'setOwnerId',
        'group_id' => 'setGroupId',
        'video_id' => 'setVideoId',
        'created' => 'setCreated',
        'sort_order' => 'setSortOrder',
        'width' => 'setWidth',
        'height' => 'setHeight',
        'duration' => 'setDuration',
        'original' => 'setOriginal',
        'state' => 'setState',
        'deleted' => 'setDeleted',
        'resolution_name' => 'setResolutionName',
        'static_small' => 'setStaticSmall',
        'static_medium' => 'setStaticMedium',
        'static_watermark_small' => 'setStaticWatermarkSmall',
        'static_watermark_medium' => 'setStaticWatermarkMedium',
        'small_preview' => 'setSmallPreview',
        'small_preview_gif' => 'setSmallPreviewGif',
        'watermark_small' => 'setWatermarkSmall',
        'watermark_small_gif' => 'setWatermarkSmallGif',
        'medium_preview' => 'setMediumPreview',
        'medium_preview_gif' => 'setMediumPreviewGif',
        'watermark_medium' => 'setWatermarkMedium',
        'watermark_medium_gif' => 'setWatermarkMediumGif',
        'stream480p' => 'setStream480p',
        'source_video_id' => 'setSourceVideoId',
        'is360' => 'setIs360',
        'stereo_mode' => 'setStereoMode',
        'region' => 'setRegion',
        'is_souvenir' => 'setIsSouvenir',
        'download_link' => 'setDownloadLink'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'owner_id' => 'getOwnerId',
        'group_id' => 'getGroupId',
        'video_id' => 'getVideoId',
        'created' => 'getCreated',
        'sort_order' => 'getSortOrder',
        'width' => 'getWidth',
        'height' => 'getHeight',
        'duration' => 'getDuration',
        'original' => 'getOriginal',
        'state' => 'getState',
        'deleted' => 'getDeleted',
        'resolution_name' => 'getResolutionName',
        'static_small' => 'getStaticSmall',
        'static_medium' => 'getStaticMedium',
        'static_watermark_small' => 'getStaticWatermarkSmall',
        'static_watermark_medium' => 'getStaticWatermarkMedium',
        'small_preview' => 'getSmallPreview',
        'small_preview_gif' => 'getSmallPreviewGif',
        'watermark_small' => 'getWatermarkSmall',
        'watermark_small_gif' => 'getWatermarkSmallGif',
        'medium_preview' => 'getMediumPreview',
        'medium_preview_gif' => 'getMediumPreviewGif',
        'watermark_medium' => 'getWatermarkMedium',
        'watermark_medium_gif' => 'getWatermarkMediumGif',
        'stream480p' => 'getStream480p',
        'source_video_id' => 'getSourceVideoId',
        'is360' => 'getIs360',
        'stereo_mode' => 'getStereoMode',
        'region' => 'getRegion',
        'is_souvenir' => 'getIsSouvenir',
        'download_link' => 'getDownloadLink'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['owner_id'] = isset($data['owner_id']) ? $data['owner_id'] : null;
        $this->container['group_id'] = isset($data['group_id']) ? $data['group_id'] : null;
        $this->container['video_id'] = isset($data['video_id']) ? $data['video_id'] : null;
        $this->container['created'] = isset($data['created']) ? $data['created'] : null;
        $this->container['sort_order'] = isset($data['sort_order']) ? $data['sort_order'] : null;
        $this->container['width'] = isset($data['width']) ? $data['width'] : null;
        $this->container['height'] = isset($data['height']) ? $data['height'] : null;
        $this->container['duration'] = isset($data['duration']) ? $data['duration'] : null;
        $this->container['original'] = isset($data['original']) ? $data['original'] : null;
        $this->container['state'] = isset($data['state']) ? $data['state'] : null;
        $this->container['deleted'] = isset($data['deleted']) ? $data['deleted'] : null;
        $this->container['resolution_name'] = isset($data['resolution_name']) ? $data['resolution_name'] : null;
        $this->container['static_small'] = isset($data['static_small']) ? $data['static_small'] : null;
        $this->container['static_medium'] = isset($data['static_medium']) ? $data['static_medium'] : null;
        $this->container['static_watermark_small'] = isset($data['static_watermark_small']) ? $data['static_watermark_small'] : null;
        $this->container['static_watermark_medium'] = isset($data['static_watermark_medium']) ? $data['static_watermark_medium'] : null;
        $this->container['small_preview'] = isset($data['small_preview']) ? $data['small_preview'] : null;
        $this->container['small_preview_gif'] = isset($data['small_preview_gif']) ? $data['small_preview_gif'] : null;
        $this->container['watermark_small'] = isset($data['watermark_small']) ? $data['watermark_small'] : null;
        $this->container['watermark_small_gif'] = isset($data['watermark_small_gif']) ? $data['watermark_small_gif'] : null;
        $this->container['medium_preview'] = isset($data['medium_preview']) ? $data['medium_preview'] : null;
        $this->container['medium_preview_gif'] = isset($data['medium_preview_gif']) ? $data['medium_preview_gif'] : null;
        $this->container['watermark_medium'] = isset($data['watermark_medium']) ? $data['watermark_medium'] : null;
        $this->container['watermark_medium_gif'] = isset($data['watermark_medium_gif']) ? $data['watermark_medium_gif'] : null;
        $this->container['stream480p'] = isset($data['stream480p']) ? $data['stream480p'] : null;
        $this->container['source_video_id'] = isset($data['source_video_id']) ? $data['source_video_id'] : null;
        $this->container['is360'] = isset($data['is360']) ? $data['is360'] : null;
        $this->container['stereo_mode'] = isset($data['stereo_mode']) ? $data['stereo_mode'] : null;
        $this->container['region'] = isset($data['region']) ? $data['region'] : null;
        $this->container['is_souvenir'] = isset($data['is_souvenir']) ? $data['is_souvenir'] : null;
        $this->container['download_link'] = isset($data['download_link']) ? $data['download_link'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['owner_id'] === null) {
            $invalidProperties[] = "'owner_id' can't be null";
        }
        if ($this->container['group_id'] === null) {
            $invalidProperties[] = "'group_id' can't be null";
        }
        if ($this->container['video_id'] === null) {
            $invalidProperties[] = "'video_id' can't be null";
        }
        if ($this->container['created'] === null) {
            $invalidProperties[] = "'created' can't be null";
        }
        if ($this->container['sort_order'] === null) {
            $invalidProperties[] = "'sort_order' can't be null";
        }
        if ($this->container['width'] === null) {
            $invalidProperties[] = "'width' can't be null";
        }
        if ($this->container['height'] === null) {
            $invalidProperties[] = "'height' can't be null";
        }
        if ($this->container['duration'] === null) {
            $invalidProperties[] = "'duration' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets owner_id
     *
     * @return string
     */
    public function getOwnerId()
    {
        return $this->container['owner_id'];
    }

    /**
     * Sets owner_id
     *
     * @param string $owner_id The UUID of the owning account.
     *
     * @return $this
     */
    public function setOwnerId($owner_id)
    {
        $this->container['owner_id'] = $owner_id;

        return $this;
    }

    /**
     * Gets group_id
     *
     * @return string
     */
    public function getGroupId()
    {
        return $this->container['group_id'];
    }

    /**
     * Sets group_id
     *
     * @param string $group_id The UUID of the group this photo is in.
     *
     * @return $this
     */
    public function setGroupId($group_id)
    {
        $this->container['group_id'] = $group_id;

        return $this;
    }

    /**
     * Gets video_id
     *
     * @return string
     */
    public function getVideoId()
    {
        return $this->container['video_id'];
    }

    /**
     * Sets video_id
     *
     * @param string $video_id The UUID of the video
     *
     * @return $this
     */
    public function setVideoId($video_id)
    {
        $this->container['video_id'] = $video_id;

        return $this;
    }

    /**
     * Gets created
     *
     * @return int
     */
    public function getCreated()
    {
        return $this->container['created'];
    }

    /**
     * Sets created
     *
     * @param int $created The unix timestamp this video was created.
     *
     * @return $this
     */
    public function setCreated($created)
    {
        $this->container['created'] = $created;

        return $this;
    }

    /**
     * Gets sort_order
     *
     * @return string
     */
    public function getSortOrder()
    {
        return $this->container['sort_order'];
    }

    /**
     * Sets sort_order
     *
     * @param string $sort_order The original filename of the video.
     *
     * @return $this
     */
    public function setSortOrder($sort_order)
    {
        $this->container['sort_order'] = $sort_order;

        return $this;
    }

    /**
     * Gets width
     *
     * @return int
     */
    public function getWidth()
    {
        return $this->container['width'];
    }

    /**
     * Sets width
     *
     * @param int $width The Width of the original video
     *
     * @return $this
     */
    public function setWidth($width)
    {
        $this->container['width'] = $width;

        return $this;
    }

    /**
     * Gets height
     *
     * @return int
     */
    public function getHeight()
    {
        return $this->container['height'];
    }

    /**
     * Sets height
     *
     * @param int $height The Height of the original video
     *
     * @return $this
     */
    public function setHeight($height)
    {
        $this->container['height'] = $height;

        return $this;
    }

    /**
     * Gets duration
     *
     * @return string
     */
    public function getDuration()
    {
        return $this->container['duration'];
    }

    /**
     * Sets duration
     *
     * @param string $duration A string describing the duration of the video. Extract from video metadata data.
     *
     * @return $this
     */
    public function setDuration($duration)
    {
        $this->container['duration'] = $duration;

        return $this;
    }

    /**
     * Gets original
     *
     * @return string|null
     */
    public function getOriginal()
    {
        return $this->container['original'];
    }

    /**
     * Sets original
     *
     * @param string|null $original The path to the original video.
     *
     * @return $this
     */
    public function setOriginal($original)
    {
        $this->container['original'] = $original;

        return $this;
    }

    /**
     * Gets state
     *
     * @return string|null
     */
    public function getState()
    {
        return $this->container['state'];
    }

    /**
     * Sets state
     *
     * @param string|null $state I don't know?
     *
     * @return $this
     */
    public function setState($state)
    {
        $this->container['state'] = $state;

        return $this;
    }

    /**
     * Gets deleted
     *
     * @return bool|null
     */
    public function getDeleted()
    {
        return $this->container['deleted'];
    }

    /**
     * Sets deleted
     *
     * @param bool|null $deleted If this video has been deleted or not
     *
     * @return $this
     */
    public function setDeleted($deleted)
    {
        $this->container['deleted'] = $deleted;

        return $this;
    }

    /**
     * Gets resolution_name
     *
     * @return string|null
     */
    public function getResolutionName()
    {
        return $this->container['resolution_name'];
    }

    /**
     * Sets resolution_name
     *
     * @param string|null $resolution_name A human readable name for this video.
     *
     * @return $this
     */
    public function setResolutionName($resolution_name)
    {
        $this->container['resolution_name'] = $resolution_name;

        return $this;
    }

    /**
     * Gets static_small
     *
     * @return string|null
     */
    public function getStaticSmall()
    {
        return $this->container['static_small'];
    }

    /**
     * Sets static_small
     *
     * @param string|null $static_small An image thumbnail of the video.
     *
     * @return $this
     */
    public function setStaticSmall($static_small)
    {
        $this->container['static_small'] = $static_small;

        return $this;
    }

    /**
     * Gets static_medium
     *
     * @return string|null
     */
    public function getStaticMedium()
    {
        return $this->container['static_medium'];
    }

    /**
     * Sets static_medium
     *
     * @param string|null $static_medium An image thumbnail (Medium Sized) of the video.
     *
     * @return $this
     */
    public function setStaticMedium($static_medium)
    {
        $this->container['static_medium'] = $static_medium;

        return $this;
    }

    /**
     * Gets static_watermark_small
     *
     * @return string|null
     */
    public function getStaticWatermarkSmall()
    {
        return $this->container['static_watermark_small'];
    }

    /**
     * Sets static_watermark_small
     *
     * @param string|null $static_watermark_small An image thumbnail of the video. Contains a watermark.
     *
     * @return $this
     */
    public function setStaticWatermarkSmall($static_watermark_small)
    {
        $this->container['static_watermark_small'] = $static_watermark_small;

        return $this;
    }

    /**
     * Gets static_watermark_medium
     *
     * @return string|null
     */
    public function getStaticWatermarkMedium()
    {
        return $this->container['static_watermark_medium'];
    }

    /**
     * Sets static_watermark_medium
     *
     * @param string|null $static_watermark_medium An image thumbnail (Medium Sized) of the video. Contains a watermark.
     *
     * @return $this
     */
    public function setStaticWatermarkMedium($static_watermark_medium)
    {
        $this->container['static_watermark_medium'] = $static_watermark_medium;

        return $this;
    }

    /**
     * Gets small_preview
     *
     * @return string|null
     */
    public function getSmallPreview()
    {
        return $this->container['small_preview'];
    }

    /**
     * Sets small_preview
     *
     * @param string|null $small_preview A MP4 preview of the video. Small sized.
     *
     * @return $this
     */
    public function setSmallPreview($small_preview)
    {
        $this->container['small_preview'] = $small_preview;

        return $this;
    }

    /**
     * Gets small_preview_gif
     *
     * @return string|null
     */
    public function getSmallPreviewGif()
    {
        return $this->container['small_preview_gif'];
    }

    /**
     * Sets small_preview_gif
     *
     * @param string|null $small_preview_gif A GIF preview of the video. Small sized. Preferabbly use the MP4 version
     *
     * @return $this
     */
    public function setSmallPreviewGif($small_preview_gif)
    {
        $this->container['small_preview_gif'] = $small_preview_gif;

        return $this;
    }

    /**
     * Gets watermark_small
     *
     * @return string|null
     */
    public function getWatermarkSmall()
    {
        return $this->container['watermark_small'];
    }

    /**
     * Sets watermark_small
     *
     * @param string|null $watermark_small An MP4 watermarked preview of the video. Thumbnail sized. Preferabbly use this instead of a GIF.
     *
     * @return $this
     */
    public function setWatermarkSmall($watermark_small)
    {
        $this->container['watermark_small'] = $watermark_small;

        return $this;
    }

    /**
     * Gets watermark_small_gif
     *
     * @return string|null
     */
    public function getWatermarkSmallGif()
    {
        return $this->container['watermark_small_gif'];
    }

    /**
     * Sets watermark_small_gif
     *
     * @param string|null $watermark_small_gif An GIF watermarked preview of the video. Medium sized. Preferabbly use the MP4.
     *
     * @return $this
     */
    public function setWatermarkSmallGif($watermark_small_gif)
    {
        $this->container['watermark_small_gif'] = $watermark_small_gif;

        return $this;
    }

    /**
     * Gets medium_preview
     *
     * @return string|null
     */
    public function getMediumPreview()
    {
        return $this->container['medium_preview'];
    }

    /**
     * Sets medium_preview
     *
     * @param string|null $medium_preview A Medium sized MP4 preview of the video.
     *
     * @return $this
     */
    public function setMediumPreview($medium_preview)
    {
        $this->container['medium_preview'] = $medium_preview;

        return $this;
    }

    /**
     * Gets medium_preview_gif
     *
     * @return string|null
     */
    public function getMediumPreviewGif()
    {
        return $this->container['medium_preview_gif'];
    }

    /**
     * Sets medium_preview_gif
     *
     * @param string|null $medium_preview_gif A Medium sized GIF preview of the video. Preferabbly use the MP4
     *
     * @return $this
     */
    public function setMediumPreviewGif($medium_preview_gif)
    {
        $this->container['medium_preview_gif'] = $medium_preview_gif;

        return $this;
    }

    /**
     * Gets watermark_medium
     *
     * @return string|null
     */
    public function getWatermarkMedium()
    {
        return $this->container['watermark_medium'];
    }

    /**
     * Sets watermark_medium
     *
     * @param string|null $watermark_medium An MP4 watermarked preview of the video. Medium sized. Preferabbly use this instead of a GIF.
     *
     * @return $this
     */
    public function setWatermarkMedium($watermark_medium)
    {
        $this->container['watermark_medium'] = $watermark_medium;

        return $this;
    }

    /**
     * Gets watermark_medium_gif
     *
     * @return string|null
     */
    public function getWatermarkMediumGif()
    {
        return $this->container['watermark_medium_gif'];
    }

    /**
     * Sets watermark_medium_gif
     *
     * @param string|null $watermark_medium_gif An GIF watermarked preview of the video. Medium sized. Preferabbly use the MP4.
     *
     * @return $this
     */
    public function setWatermarkMediumGif($watermark_medium_gif)
    {
        $this->container['watermark_medium_gif'] = $watermark_medium_gif;

        return $this;
    }

    /**
     * Gets stream480p
     *
     * @return string|null
     */
    public function getStream480p()
    {
        return $this->container['stream480p'];
    }

    /**
     * Sets stream480p
     *
     * @param string|null $stream480p A stream optimized version of the original video. Sized at 480p.
     *
     * @return $this
     */
    public function setStream480p($stream480p)
    {
        $this->container['stream480p'] = $stream480p;

        return $this;
    }

    /**
     * Gets source_video_id
     *
     * @return string|null
     */
    public function getSourceVideoId()
    {
        return $this->container['source_video_id'];
    }

    /**
     * Sets source_video_id
     *
     * @param string|null $source_video_id If this is a copied video, SourceVideoId will hold a reference to the original video.
     *
     * @return $this
     */
    public function setSourceVideoId($source_video_id)
    {
        $this->container['source_video_id'] = $source_video_id;

        return $this;
    }

    /**
     * Gets is360
     *
     * @return bool|null
     */
    public function getIs360()
    {
        return $this->container['is360'];
    }

    /**
     * Sets is360
     *
     * @param bool|null $is360 Is this Video a 360 Video
     *
     * @return $this
     */
    public function setIs360($is360)
    {
        $this->container['is360'] = $is360;

        return $this;
    }

    /**
     * Gets stereo_mode
     *
     * @return string|null
     */
    public function getStereoMode()
    {
        return $this->container['stereo_mode'];
    }

    /**
     * Sets stereo_mode
     *
     * @param string|null $stereo_mode If this is a 360 Video, this will describe the stereo mode of it.
     *
     * @return $this
     */
    public function setStereoMode($stereo_mode)
    {
        $this->container['stereo_mode'] = $stereo_mode;

        return $this;
    }

    /**
     * Gets region
     *
     * @return \OpenAPI\Client\Model\Region|null
     */
    public function getRegion()
    {
        return $this->container['region'];
    }

    /**
     * Sets region
     *
     * @param \OpenAPI\Client\Model\Region|null $region region
     *
     * @return $this
     */
    public function setRegion($region)
    {
        $this->container['region'] = $region;

        return $this;
    }

    /**
     * Gets is_souvenir
     *
     * @return bool|null
     */
    public function getIsSouvenir()
    {
        return $this->container['is_souvenir'];
    }

    /**
     * Sets is_souvenir
     *
     * @param bool|null $is_souvenir If this video is a Souvenir video.
     *
     * @return $this
     */
    public function setIsSouvenir($is_souvenir)
    {
        $this->container['is_souvenir'] = $is_souvenir;

        return $this;
    }

    /**
     * Gets download_link
     *
     * @return string|null
     */
    public function getDownloadLink()
    {
        return $this->container['download_link'];
    }

    /**
     * Sets download_link
     *
     * @param string|null $download_link A time limited download link for the original. This is a pre-signed url that forces the download header on S3.
     *
     * @return $this
     */
    public function setDownloadLink($download_link)
    {
        $this->container['download_link'] = $download_link;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}


