<?php
/**
 * AddPhotosToGroupResponseAddedPhotosTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PicThrive Internal API
 *
 * Detailed docs about our API, including hidden fields not publicly displayed.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

/**
 * AddPhotosToGroupResponseAddedPhotosTest Class Doc Comment
 *
 * @category    Class
 * @description AddPhotosToGroupResponseAddedPhotos
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AddPhotosToGroupResponseAddedPhotosTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AddPhotosToGroupResponseAddedPhotos"
     */
    public function testAddPhotosToGroupResponseAddedPhotos()
    {
    }

    /**
     * Test attribute "photo_id"
     */
    public function testPropertyPhotoId()
    {
    }

    /**
     * Test attribute "upload_url"
     */
    public function testPropertyUploadUrl()
    {
    }

    /**
     * Test attribute "expires"
     */
    public function testPropertyExpires()
    {
    }
}
