<?php
/**
 * BrandTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PicThrive Internal API
 *
 * Detailed docs about our API, including hidden fields not publicly displayed.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

/**
 * BrandTest Class Doc Comment
 *
 * @category    Class
 * @description Brand
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class BrandTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Brand"
     */
    public function testBrand()
    {
    }

    /**
     * Test attribute "owner_id"
     */
    public function testPropertyOwnerId()
    {
    }

    /**
     * Test attribute "brand_id"
     */
    public function testPropertyBrandId()
    {
    }

    /**
     * Test attribute "vanity_url"
     */
    public function testPropertyVanityUrl()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "website"
     */
    public function testPropertyWebsite()
    {
    }

    /**
     * Test attribute "booking_link"
     */
    public function testPropertyBookingLink()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "social"
     */
    public function testPropertySocial()
    {
    }

    /**
     * Test attribute "review"
     */
    public function testPropertyReview()
    {
    }

    /**
     * Test attribute "banner300"
     */
    public function testPropertyBanner300()
    {
    }

    /**
     * Test attribute "banner1280"
     */
    public function testPropertyBanner1280()
    {
    }

    /**
     * Test attribute "logo100"
     */
    public function testPropertyLogo100()
    {
    }

    /**
     * Test attribute "logo150"
     */
    public function testPropertyLogo150()
    {
    }

    /**
     * Test attribute "logo300"
     */
    public function testPropertyLogo300()
    {
    }

    /**
     * Test attribute "google_analytics"
     */
    public function testPropertyGoogleAnalytics()
    {
    }

    /**
     * Test attribute "pricing"
     */
    public function testPropertyPricing()
    {
    }

    /**
     * Test attribute "default_pricing_id"
     */
    public function testPropertyDefaultPricingId()
    {
    }

    /**
     * Test attribute "campaign"
     */
    public function testPropertyCampaign()
    {
    }

    /**
     * Test attribute "ads"
     */
    public function testPropertyAds()
    {
    }

    /**
     * Test attribute "ads_updated"
     */
    public function testPropertyAdsUpdated()
    {
    }

    /**
     * Test attribute "custom_gallery_domain"
     */
    public function testPropertyCustomGalleryDomain()
    {
    }

    /**
     * Test attribute "custom_store_prefix"
     */
    public function testPropertyCustomStorePrefix()
    {
    }

    /**
     * Test attribute "google_remarketing_code"
     */
    public function testPropertyGoogleRemarketingCode()
    {
    }

    /**
     * Test attribute "google_remarketing_label_code"
     */
    public function testPropertyGoogleRemarketingLabelCode()
    {
    }

    /**
     * Test attribute "facebook_remarketing_code"
     */
    public function testPropertyFacebookRemarketingCode()
    {
    }

    /**
     * Test attribute "remarketing_updated"
     */
    public function testPropertyRemarketingUpdated()
    {
    }
}
