<?php
/**
 * GroupTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PicThrive Internal API
 *
 * Detailed docs about our API, including hidden fields not publicly displayed.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

/**
 * GroupTest Class Doc Comment
 *
 * @category    Class
 * @description A Group.
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GroupTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Group"
     */
    public function testGroup()
    {
    }

    /**
     * Test attribute "owner_id"
     */
    public function testPropertyOwnerId()
    {
    }

    /**
     * Test attribute "brand_id"
     */
    public function testPropertyBrandId()
    {
    }

    /**
     * Test attribute "group_id"
     */
    public function testPropertyGroupId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "token"
     */
    public function testPropertyToken()
    {
    }

    /**
     * Test attribute "count"
     */
    public function testPropertyCount()
    {
    }

    /**
     * Test attribute "video_count"
     */
    public function testPropertyVideoCount()
    {
    }

    /**
     * Test attribute "thumb"
     */
    public function testPropertyThumb()
    {
    }

    /**
     * Test attribute "thumb_region"
     */
    public function testPropertyThumbRegion()
    {
    }

    /**
     * Test attribute "thumb1"
     */
    public function testPropertyThumb1()
    {
    }

    /**
     * Test attribute "thumb1_region"
     */
    public function testPropertyThumb1Region()
    {
    }

    /**
     * Test attribute "thumb2"
     */
    public function testPropertyThumb2()
    {
    }

    /**
     * Test attribute "thumb2_region"
     */
    public function testPropertyThumb2Region()
    {
    }

    /**
     * Test attribute "when_unix"
     */
    public function testPropertyWhenUnix()
    {
    }

    /**
     * Test attribute "deleted"
     */
    public function testPropertyDeleted()
    {
    }

    /**
     * Test attribute "last_updated_unix"
     */
    public function testPropertyLastUpdatedUnix()
    {
    }

    /**
     * Test attribute "created_by"
     */
    public function testPropertyCreatedBy()
    {
    }

    /**
     * Test attribute "hide_from_store"
     */
    public function testPropertyHideFromStore()
    {
    }

    /**
     * Test attribute "pricing_id"
     */
    public function testPropertyPricingId()
    {
    }

    /**
     * Test attribute "formatted_time"
     */
    public function testPropertyFormattedTime()
    {
    }

    /**
     * Test attribute "time_of_tour"
     */
    public function testPropertyTimeOfTour()
    {
    }

    /**
     * Test attribute "interaction_count"
     */
    public function testPropertyInteractionCount()
    {
    }

    /**
     * Test attribute "uploading_unix"
     */
    public function testPropertyUploadingUnix()
    {
    }
}
