<?php
/**
 * PublicPhotoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PicThrive Internal API
 *
 * Detailed docs about our API, including hidden fields not publicly displayed.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

/**
 * PublicPhotoTest Class Doc Comment
 *
 * @category    Class
 * @description PublicPhoto
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PublicPhotoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PublicPhoto"
     */
    public function testPublicPhoto()
    {
    }

    /**
     * Test attribute "owner_id"
     */
    public function testPropertyOwnerId()
    {
    }

    /**
     * Test attribute "group_id"
     */
    public function testPropertyGroupId()
    {
    }

    /**
     * Test attribute "photo_id"
     */
    public function testPropertyPhotoId()
    {
    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {
    }

    /**
     * Test attribute "small"
     */
    public function testPropertySmall()
    {
    }

    /**
     * Test attribute "watermark"
     */
    public function testPropertyWatermark()
    {
    }

    /**
     * Test attribute "watermark_small"
     */
    public function testPropertyWatermarkSmall()
    {
    }

    /**
     * Test attribute "watermark_square"
     */
    public function testPropertyWatermarkSquare()
    {
    }

    /**
     * Test attribute "sort_order"
     */
    public function testPropertySortOrder()
    {
    }

    /**
     * Test attribute "region"
     */
    public function testPropertyRegion()
    {
    }

    /**
     * Test attribute "ratio"
     */
    public function testPropertyRatio()
    {
    }

    /**
     * Test attribute "width"
     */
    public function testPropertyWidth()
    {
    }

    /**
     * Test attribute "height"
     */
    public function testPropertyHeight()
    {
    }

    /**
     * Test attribute "megapixels"
     */
    public function testPropertyMegapixels()
    {
    }

    /**
     * Test attribute "hue"
     */
    public function testPropertyHue()
    {
    }
}
