<?php
/**
 * VideoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PicThrive Internal API
 *
 * Detailed docs about our API, including hidden fields not publicly displayed.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

/**
 * VideoTest Class Doc Comment
 *
 * @category    Class
 * @description Video
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class VideoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Video"
     */
    public function testVideo()
    {
    }

    /**
     * Test attribute "owner_id"
     */
    public function testPropertyOwnerId()
    {
    }

    /**
     * Test attribute "group_id"
     */
    public function testPropertyGroupId()
    {
    }

    /**
     * Test attribute "video_id"
     */
    public function testPropertyVideoId()
    {
    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {
    }

    /**
     * Test attribute "sort_order"
     */
    public function testPropertySortOrder()
    {
    }

    /**
     * Test attribute "width"
     */
    public function testPropertyWidth()
    {
    }

    /**
     * Test attribute "height"
     */
    public function testPropertyHeight()
    {
    }

    /**
     * Test attribute "duration"
     */
    public function testPropertyDuration()
    {
    }

    /**
     * Test attribute "original"
     */
    public function testPropertyOriginal()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "deleted"
     */
    public function testPropertyDeleted()
    {
    }

    /**
     * Test attribute "resolution_name"
     */
    public function testPropertyResolutionName()
    {
    }

    /**
     * Test attribute "static_small"
     */
    public function testPropertyStaticSmall()
    {
    }

    /**
     * Test attribute "static_medium"
     */
    public function testPropertyStaticMedium()
    {
    }

    /**
     * Test attribute "static_watermark_small"
     */
    public function testPropertyStaticWatermarkSmall()
    {
    }

    /**
     * Test attribute "static_watermark_medium"
     */
    public function testPropertyStaticWatermarkMedium()
    {
    }

    /**
     * Test attribute "small_preview"
     */
    public function testPropertySmallPreview()
    {
    }

    /**
     * Test attribute "small_preview_gif"
     */
    public function testPropertySmallPreviewGif()
    {
    }

    /**
     * Test attribute "watermark_small"
     */
    public function testPropertyWatermarkSmall()
    {
    }

    /**
     * Test attribute "watermark_small_gif"
     */
    public function testPropertyWatermarkSmallGif()
    {
    }

    /**
     * Test attribute "medium_preview"
     */
    public function testPropertyMediumPreview()
    {
    }

    /**
     * Test attribute "medium_preview_gif"
     */
    public function testPropertyMediumPreviewGif()
    {
    }

    /**
     * Test attribute "watermark_medium"
     */
    public function testPropertyWatermarkMedium()
    {
    }

    /**
     * Test attribute "watermark_medium_gif"
     */
    public function testPropertyWatermarkMediumGif()
    {
    }

    /**
     * Test attribute "stream480p"
     */
    public function testPropertyStream480p()
    {
    }

    /**
     * Test attribute "source_video_id"
     */
    public function testPropertySourceVideoId()
    {
    }

    /**
     * Test attribute "is360"
     */
    public function testPropertyIs360()
    {
    }

    /**
     * Test attribute "stereo_mode"
     */
    public function testPropertyStereoMode()
    {
    }

    /**
     * Test attribute "region"
     */
    public function testPropertyRegion()
    {
    }

    /**
     * Test attribute "is_souvenir"
     */
    public function testPropertyIsSouvenir()
    {
    }

    /**
     * Test attribute "download_link"
     */
    public function testPropertyDownloadLink()
    {
    }
}
