<?php
/**
 * GroupApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PicThrive Internal API
 *
 * Detailed docs about our API, including hidden fields not publicly displayed.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;

/**
 * GroupApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class GroupApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createGroup
     *
     * Create an new Group..
     *
     */
    public function testCreateGroup()
    {
    }

    /**
     * Test case for createUploadPhotoRequest
     *
     * Upload a photo.
     *
     */
    public function testCreateUploadPhotoRequest()
    {
    }

    /**
     * Test case for deleteGroup
     *
     * Delete the Group.
     *
     */
    public function testDeleteGroup()
    {
    }

    /**
     * Test case for getGroup
     *
     * Gets a Group..
     *
     */
    public function testGetGroup()
    {
    }

    /**
     * Test case for listGroupPhotos
     *
     * List photos.
     *
     */
    public function testListGroupPhotos()
    {
    }

    /**
     * Test case for listGroupVideos
     *
     * List videos.
     *
     */
    public function testListGroupVideos()
    {
    }

    /**
     * Test case for listGroups
     *
     * List Groups.
     *
     */
    public function testListGroups()
    {
    }

    /**
     * Test case for markGroupAsUploading
     *
     * Update Upload Status.
     *
     */
    public function testMarkGroupAsUploading()
    {
    }

    /**
     * Test case for searchForGroupByToken
     *
     * Search for Group by Token.
     *
     */
    public function testSearchForGroupByToken()
    {
    }

    /**
     * Test case for updateGroup
     *
     * Update a Group.
     *
     */
    public function testUpdateGroup()
    {
    }

    /**
     * Test case for zipGroupPhotos
     *
     * Zip Photos.
     *
     */
    public function testZipGroupPhotos()
    {
    }
}
