<?php
/**
 * PhotoApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PicThrive Internal API
 *
 * Detailed docs about our API, including hidden fields not publicly displayed.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;

/**
 * PhotoApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PhotoApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createUploadPhotoRequest
     *
     * Upload a photo.
     *
     */
    public function testCreateUploadPhotoRequest()
    {
    }

    /**
     * Test case for deletePhoto
     *
     * Delete a Photo.
     *
     */
    public function testDeletePhoto()
    {
    }

    /**
     * Test case for getPhoto
     *
     * Get a Photo.
     *
     */
    public function testGetPhoto()
    {
    }

    /**
     * Test case for listGroupPhotos
     *
     * List photos.
     *
     */
    public function testListGroupPhotos()
    {
    }

    /**
     * Test case for markGroupAsUploading
     *
     * Update Upload Status.
     *
     */
    public function testMarkGroupAsUploading()
    {
    }

    /**
     * Test case for updatePhoto
     *
     * Copy or Move a Photo.
     *
     */
    public function testUpdatePhoto()
    {
    }

    /**
     * Test case for zipGroupPhotos
     *
     * Zip Photos.
     *
     */
    public function testZipGroupPhotos()
    {
    }
}
